# Generated by Django 2.2.5 on 2019-09-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
