# Generated by Django 2.2.1 on 2019-09-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_emailaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='myEmail',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Mytag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myTag', models.CharField(max_length=20)),
                ('emailAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.EmailAccount')),
            ],
        ),
    ]
