# Generated by Django 2.2.1 on 2019-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_recenttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_title', models.CharField(max_length=500)),
            ],
        ),
    ]
