# Generated by Django 2.2.1 on 2019-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_kmtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentKmTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_KM_notie', models.CharField(max_length=120)),
            ],
        ),
    ]
