# Generated by Django 2.1.1 on 2019-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20190929_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmtitle',
            name='km_link',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kmtitle',
            name='km_title',
            field=models.CharField(max_length=500),
        ),
    ]
