# Generated by Django 2.1.1 on 2019-09-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0009_auto_20190930_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledata',
            name='link',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kmtitle',
            name='km_link',
            field=models.IntegerField(),
        ),
    ]
