# Generated by Django 2.1.1 on 2019-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_auto_20190930_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titledata',
            name='link',
            field=models.IntegerField(),
        ),
    ]
