# Generated by Django 2.1.1 on 2019-09-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0011_auto_20190930_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentKmTitle',
        ),
        migrations.DeleteModel(
            name='RecentTitle',
        ),
    ]
