# Generated by Django 2.2.1 on 2019-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0012_auto_20190930_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_link', models.IntegerField()),
                ('km_link', models.IntegerField()),
            ],
        ),
    ]
